### PR TITLE
I32 Constant

### PR DESCRIPTION
**Pull request by Checkmate50**
Addition for my own sanity, though touches a lot of files.

### CODE REVIEW

**Comment by sampsyo** [comment]
I won't pretend to fully understand the diff (the footprint is pretty large, perhaps because it includes some other PRs in here too?), but adding such a constant node seems like a lovely idea to me!

**Comment by od0x0** [comment]
The original intention for the type id field in the constants was to allow specifying what type you wanted it to be (within 64 bytes). i64 vs u64 was just to make rust happy.

**Comment by Checkmate50** [comment]
Sorry, you absolutely can put the `i32` on the buffer, but I wanted the test to be self-contained in that you define the constant in code (also helped me not have to disentangle constants for local vs gpu details).  Basically I want to make [this example](https://github.com/cucapra/caiman/blob/scheduling1/caiman-test/scheduling/gpu_external_baseline.cair) work without having to read from the buffer and use a constant instead.  Now that I rewrote the test suite, this is less of a problem, but this is such a quick hack I don't care much either way.

**Comment by Checkmate50** [comment]
As for the making Rust happy, totally agree.  However, without the types being unified, the parser is sad when translating from assembly, so this felt like the quickest dumbest way to make what I wanted.

**Pull request merged**
