### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by Checkmate50**
Added a bunch of examples and some testing style tweaks to help with debugging

### CODE REVIEW

**Comment by sampsyo** [comment]
All looks good from a high-level look! Glad to see there are so many examples/tests now.

Are there particular things we should be looking for in the new tests?

**Comment by Checkmate50** [comment]
Thanks so much!  The tests I'm adding are doing the very boring thing of testing "each operation" in Caiman, sort of as minimally as I could make it.  They are designed to test explication more than the language, but I figured they were close enough to testing the language they make a good starting point.  With the updates to the type system proposed, I want to design more language-focused tests to get a better sense of the practical bounds of the theory though.

**Comment by Checkmate50** [comment]
Now that I'm updating the test suite, I intend to make more folders/structure (at some point at least); I didn't come into this intending to design more careful tests of the language, so I should probably rethink that a tad.

**Comment by sampsyo** [comment]
OK, sounds good!

**Pull request merged**
