### PR TITLE
Explication Restructure

### PR DESCRIPTION
**Pull request by Checkmate50**
This PR adds in some sweeping changes to the organization of explication and debugging.  The most important change is the addition of a new IR and associated pass (oof) between the assembly AST and typechecking.  The new IR is titled `expir` to distinguish it from the fully explicated ready-to-typecheck IR, and lives in the `explication` module.

The other changes (hopefully improvements) this PR makes can be roughly summarized as follows:
* All the explication logic is pushed into the `explication` module
  - Holes have been moved to `explication`
  - There are now separate contexts for explication and assembly, which should hopefully reduce complexity when trying to lower stuff
* Lowering is much more macro'd as a whole, specifically for nodes.  We should consider making Tail edges similarly macro'd, because this makes it a lot easier to futz with the definitions of the language
* Debugging information is now "passed down" from the assembly, and error messages now print information based on the original assembly code names
* Explication, as an explicit pass, is now setup to do "partial explication" while I add the pieces.  These partial explication steps are currently disabled to avoid confusion with what works and what doesn't here.

### CODE REVIEW

**Comment by Checkmate50** [comment]
For review, I would appreciate specifically a review on `codegen` and the `high-level-caiman` module changes.  I would also appreciate an attempt to run and see how error messages "feel" in the current form.

**Review by stephenverderame — DISMISSED** [review]
I mostly focused on codegen, frontend, and typechecking, but it looks good to me

**Comment by stephenverderame** [comment]
Actually, I take that back lol. Belated April Fools? When I try to build the branch I get the folloiwing error: 
```
error[E0446]: private type `explication::context::ScheduleScopeData` in public interface
   --> src/explication/context/instate.rs:66:5
    |
66  |     pub fn get_latest_scope(&self) -> &ScheduleScopeData {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: src/explication/context.rs:113:1
    |
113 | struct ScheduleScopeData {
    | ------------------------ `explication::context::ScheduleScopeData` declared as private

error[E0446]: private type `explication::context::ScheduleScopeData` in public interface
   --> src/explication/context/instate.rs:70:5
    |
70  |     pub fn get_latest_scope_mut(&mut self) -> &mut ScheduleScopeData {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: src/explication/context.rs:113:1
    |
113 | struct ScheduleScopeData {
    | ------------------------ `explication::context::ScheduleScopeData` declared as private
```

**Comment by Checkmate50** [comment]
That's so interesting, I don't get such an error even when compiling after a `cargo clean`.  That being said, I pushed a change to make this struct public, since it's a fair message to get, sorry for the trouble!

**Review by stephenverderame — APPROVED** [review]
That is indeed strange. Thanks for the fix, it looks good

**Pull request merged**
