### PR TITLE
Bunch of Examples

### PR DESCRIPTION
**Pull request by Checkmate50**
Some parser fixes and a bunch of examples.  Note that `cargo-check` is a convenience tool and may or may not work on a given PR.  Note also that the `scheduling` tests are expected to fail at the moment.

### CODE REVIEW

**Comment by sampsyo** [comment]
Looks awesome! One silly question: are the `*.cair` files in `caiman-check/src/` doing anything? (Perhaps they are sample inputs to be used with `caiman-check`?)

**Comment by Checkmate50** [comment]
Yep, that's all it is!  Just a setup for me to build and run programs, ensure they're type-checking and doing what I want.  I separated from `caiman-test` so that I could work in my own little world.

**Comment by od0x0** [comment]
Is the issue that you don't want to worry about breaking build.rs and causing collateral damage to other tests? Unless there's some other reason I'm missing, I think a feature flag for caiman-test might be a better option. It's going to be tricky to remember to run all the tests if some are in the thing called -test and others are in the thing called -check

**Comment by Checkmate50** [comment]
The intention is not to make `caiman-check` be anything interesting (really it shouldn't even be on the main branch in a sense), it's just a place I can run code to experiment with stuff.  Seemed easier to just make a folder than to fiddle with options and/or imply that there's anything useful going on (`caiman-check` may or may not compile on a given PR, for example)

**Comment by od0x0** [comment]
I think what I meant to say is that I don't see the value here. If it's just meant to be a personal tool, then it should just be that and we should make sure caiman works outside of its own directory. If you're using it to test things of the compiler and you're ever at an intermediate point where it's not broken, then that should just be a test. If a test is ever in a state where they are broken, then we should just disable them via a build/run flag. The main value of tests is communication imo, and having something in a perpetual half-broken state sends mixed messages.

Generally, now that we're starting to have multiple people working on it again, I want to avoid half-baked things and minefields in main. I regret caiman-ref, for instance.

**Comment by od0x0** [comment]
Maybe you could add it as an explicit "experimental" directory for caiman-test?

**Comment by Checkmate50** [comment]
I like the first suggestion I suppose, I'll just make my own directory, since I agree that should work easily enough.

**Comment by Checkmate50** [comment]
Should be removed now, I feel dumb I didn't think of that myself tbh

**Review by od0x0 — APPROVED** [review]

**Pull request merged**
